### ISSUE TITLE
[Question] Is it possible to browserify kad-traverse?

### ISSUE THREAD

**Issue by zanetu** [kadtools/kad-traverse#3]
I wonder if it's technically possible to [browserify](https://github.com/substack/node-browserify) `kad-traverse` so that I can develop browser-side applications (e.g. [userscripts](https://en.wikipedia.org/wiki/Greasemonkey)) with `kad-traverse` as well as [`kad-webrtc`](https://github.com/omphalos/kad-webrtc). (Will `kad-traverse` support `kad-webrtc` by the way?)

**Comment by gordonwritescode** [comment]
As of right now it only supports the UDP transport (and barely at that) and so it is not browserfiable in any meaningful way. 

However, I think that ultimately it would be great if we could expand that. The recent kad updates have been focused on modularity and better interfaces for extending functionality for the purpose of being able to "plug and play" these types of extensions. 

If it doesn't get implemented as part of this module, then certainly it will somewhere else.

**Comment by gordonwritescode** [comment]
After some poking around, looks like we should be able to write a transport adapter that uses this: https://developer.mozilla.org/en-US/docs/Web/API/TCP_Socket_API

Then we would would be pretty close to kad-traverse working for your use case, however the STUN and TURN client implementations we are using only support UDP. 

I wonder if @nicojanssens has an idea of the level of effort to get his implementations working over TCP.

**Comment by zanetu** [comment]
[**@gordonwritescode**](https://github.com/gordonwritescode) commented on [Jan 17, 2016, 6:47 PM EST](https://github.com/kadtools/kad-traverse/issues/3#issuecomment-172396330 "2016-01-17T23:47:39Z - Replied by Github Comment Enhancer"):
> After some poking around, looks like we should be able to write a transport adapter that uses this: [https://developer.mozilla.org/en-US/docs/Web/API/TCP_Socket_API](https://developer.mozilla.org/en-US/docs/Web/API/TCP_Socket_API)
> 
> Then we would would be pretty close to kad-traverse working for your use case, however the STUN and TURN client implementations we are using only support UDP. 
> 
> I wonder if [@nicojanssens](https://github.com/nicojanssens) has an idea of the level of effort to get the implementations working over TCP.

Sorry for replying late. I've been quite busy these days. 

Thanks for all the research you've done. According to the link you provided, however, TCP Socket API is only available on Firefox OS platform at present and `it is not supported widely across browsers`. 

Anyway, please let me know whenever you have an idea on this issue.

**Comment by gordonwritescode** [comment]
Ah, yes, though chromium has a similar API for extensions. I'll keep digging and keep you posted.

**Comment by nicojanssens** [comment]
Hey @gordonwritescode,

I've been quite busy lately. Will increase the priority of the TCP integration in my STUN/TURN libs. I keep you posted.
