### ISSUE TITLE
Can not start kad node with traverse

### ISSUE THREAD

**Issue by bolsunovskyi** [kadtools/kad-traverse#7]
When I trying to start node with turn and stun traverse I got an error:

 :kad: {info} node created with nodeID 813eb5e8d513bb9043e4d4ec3f715104f9f8aeb3
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRNOTAVAIL 31.202.30.76:1337
    at Object.exports._errnoException (util.js:860:11)
    at exports._exceptionWithHostPort (util.js:883:20)
    at dgram.js:213:18
    at doNTCallback3 (node.js:461:9)
    at process._tickCallback (node.js:367:17)

Can you help me fix it ?

**Comment by iMihael** [comment]
My code:

var kad = require('kad'),
    traverse = require('kad-traverse');

var dht;

var contact = kad.contacts.AddressPortContact({
    address: '127.0.0.0',
    port: 1337
});

var NatTransport = traverse.TransportDecorator(kad.transports.UDP);

var transport = new NatTransport(contact, {
    traverse: {
        stun: {
            server: {
                address: "..."
            }
        },
        turn: {
            server: {
                address: "..."
            }
        }
    }
});


//var transport = kad.transports.UDP(contact);

module.exports = {
    init: function(){
        dht = new kad.Node({
            transport: transport,
            storage: kad.storage.FS(__dirname + '/../storage')
        });

        return dht;
    }
};

**Comment by gordonwritescode** [comment]
Ah, yes that's a bug. This module finds your public IP and replaces your node's contact info (including address) *before* the transport opens, which causes it to attempt to bind to your public IP which is where that error comes from. 

Good news is that you're punching out successfully. I'll try to issue a bug fix by tomorrow. Thanks for the report.
